//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLSLms
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseUnit
    {
        public CourseUnit()
        {
            this.CourseUnitStatus = new HashSet<CourseUnitStatu>();
        }
    
        public long unit_id { get; set; }
        public long courseid { get; set; }
        public byte unit_type { get; set; }
        public int unit_order { get; set; }
        public string unit_content { get; set; }
        public string unit_path_url { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<long> modified_by { get; set; }
        public string unit_name { get; set; }
        public Nullable<byte> sub_type { get; set; }
        public Nullable<long> assessment_id { get; set; }
        public int audio_delay { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<CourseUnitStatu> CourseUnitStatus { get; set; }
    }
}
