//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLSLms
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseUnitStatu
    {
        public long CourseUnitStatusID { get; set; }
        public long UnitId { get; set; }
        public long CourseId { get; set; }
        public byte UnitStatus { get; set; }
        public System.DateTime DateLastAccessed { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public long UserID { get; set; }
        public bool Bookmark { get; set; }
        public string Notes { get; set; }
        public int Video_Time { get; set; }
    
        public virtual CourseUnit CourseUnit { get; set; }
    }
}
